fix duplicate virtualenv declaration
Package pythin-virtualenv is declared in th epythin module, which puppetboard uses. This will cause an error when applying the catalog:

Error: Failed to apply catalog: Cannot alias Package[virtualenv] to ["python-virtualenv", :apt] at /etc/puppetlabs/code/environments/production/modules/python/manifests/install.pp:53; resource ["Package", "python-virtualenv", :apt] already declared at /etc/puppetlabs/code/environments/production/modules/puppetboard/manifests/init.pp:282

This fixes this issue, virtualenv is installed successfully.